

PART 1 OF 2 : LINEAR REGRESSION MULTI VARIABLE


This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. 
Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,


**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**

In [37]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [38]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [39]:
df.columns = np.array(['experience','test_score','interview_score','salary'])
df.experience = ['NaN','NaN',5,2,7,3,10,11]
df.loc[df['experience'] == 'NaN','experience'] = np.nan
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2          5         6.0                7   60000
3          2        10.0               10   65000
4          7         9.0                6   70000
5          3         7.0               10   62000
6         10         NaN                7   72000
7         11         7.0                8   80000

In [40]:
df.experience.median()

6.0

In [41]:
df.test_score.median()

8.0

In [42]:
df.experience = df.experience.fillna(df.experience.median())
df.test_score = df.test_score.fillna(df.test_score.median())
df

experience  test_score  interview_score  salary
0         6.0         8.0                9   50000
1         6.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         8.0                7   72000
7        11.0         7.0                8   80000

In [45]:
lreg = linear_model.LinearRegression()
lreg.fit(df.drop('salary',axis='columns'),df.salary)

LinearRegression()

In [46]:
lreg.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [48]:
reg.intercept_

11869.91869918695

In [49]:
m1 = lreg.coef_[0]
m2 =  lreg.coef_[1]
m3 = lreg.coef_[2]
b = reg.intercept_

#2 yr experience, 9 test score, 6 interview score
x1 = 2
x2 = 9
x3 = 6
y = m1*x1 + m2*x2 + m3*x3 + b
print("Prediction for 2 yr experience, 9 test score, 6 interview score = ",y)

Prediction for 2 yr experience, 9 test score, 6 interview score =  47056.91056910569


In [50]:
lreg.predict([[2,9,6]])

array([47056.91056911])

In [51]:
#12 yr experience, 10 test score, 10 interview score
x1 = 12
x2 = 10
x3 = 10
y = m1*x1 + m2*x2 + m3*x3 + b
print("12 yr experience, 10 test score, 10 interview score = ",y)

12 yr experience, 10 test score, 10 interview score =  88227.64227642279


In [52]:
lreg.predict([[12,10,10]])

array([88227.64227642])